apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-node
  namespace: staging-scraper
  labels:
    name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-node
  template:
    metadata:
      labels:
        app: staging-node
    spec:
      containers:
      - name: staging-node
        image: us-docker.pkg.dev/nextgem-selenium/staging/middleman:v0.0.10
        ports:
        - containerPort: 3000
        # volumeMounts:
        # - name: data
        #   mountPath: /data
        #   readOnly: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      restartPolicy: Always
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: redis-data
