apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-staging
  labels:
    name: node-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-staging
  template:
    metadata:
      labels:
        app: node-staging
    spec:
      containers:
      - name: node-staging
        image: us-central1-docker.pkg.dev/nextgem-selenium/request-queue/middleman:v0.0.6
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
      restartPolicy: Always
