apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
spec:
  replicas: 30
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/nextgem-selenium/scraper/selenium-worker:v0.0.2
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
      restartPolicy: Always
