apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-worker
  labels:
    name: selenium-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: selenium-worker
  template:
    metadata:
      labels:
        app: selenium-worker
    spec:
      containers:
      - name: selenium-worker
        image: us-central1-docker.pkg.dev/nextgem-selenium/scraper/selenium-worker:v0.0.2
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "2Gi"
            cpu: "3"
          limits:
            memory: "4Gi"
            cpu: "3"
      restartPolicy: Always
