apiVersion: v1
kind: Service
metadata:
  name: selenium-worker
  labels:
    service: selenium-worker
spec:
  selector:
    app: selenium-worker
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 5000
