apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/nextgem-selenium/scraper/selenium-worker:v0.0.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Always
